### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Nizuky** [visnkmr/file_explorer#62]
ISSUE:

encountering _java.lang.IllegalArgumentException_

messages.logfile:

[messages.log](https://github.com/visnkmr/file_explorer/files/12706366/messages.log)

**Comment by visnkmr** [comment]
Hey, On which version of android did you ensure the issue with our app, that is available only on amazon appstore? Or is it on a fire TV? From the log messages it seems that you reported the issue in the wrong repo? Please do so say so if I'm wrong.
